//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueFalseQuiz.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrueFalseQuiz.Strings.AppResources - Copy", typeof(AppResources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string FalseButtonText {
            get {
                return ResourceManager.GetString("FalseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your final score is: {0} out of {1} | {0} is the score, {1} is the total questions.
        /// </summary>
        internal static string FinalScore {
            get {
                return ResourceManager.GetString("FinalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain is a democracy..
        /// </summary>
        internal static string QuestionFive {
            get {
                return ResourceManager.GetString("QuestionFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain is below of USA..
        /// </summary>
        internal static string QuestionFour {
            get {
                return ResourceManager.GetString("QuestionFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain has one official language..
        /// </summary>
        internal static string QuestionOne {
            get {
                return ResourceManager.GetString("QuestionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaniards eat TACOS..
        /// </summary>
        internal static string QuestionThree {
            get {
                return ResourceManager.GetString("QuestionThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain’s national anthem has no words..
        /// </summary>
        internal static string QuestionTwo {
            get {
                return ResourceManager.GetString("QuestionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz finished!.
        /// </summary>
        internal static string QuizFinishedText {
            get {
                return ResourceManager.GetString("QuizFinishedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string TrueButtonText {
            get {
                return ResourceManager.GetString("TrueButtonText", resourceCulture);
            }
        }
    }
}
